# -*- coding: utf-8 -*-
"""ML Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVx27dOOgAi_Eg0ho6jeYEioYbRZTw02
"""

!nvidia-smi

# data preprocessing for google colab
!unzip finalAssignment_musicDataset.zip

!unzip finalAssignment_GPT.zip

!pip install mido pydub simpleaudio

# extractMelodies.py
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 25 21:10:09 2024

@author: Giovanni Di Liberto
See description in the assignment instructions.
"""

import os
import shutil

# Define the source directory and the target directory
source_dir = '/content/finalAssignment_musicDataset/BiMMuDa'  # Current directory
target_dir = 'musicDatasetOriginal'

# Create the target directory if it doesn't exist
if not os.path.exists(target_dir):
    os.makedirs(target_dir)

# Walk through all subdirectories
for root, dirs, files in os.walk(source_dir):
    for file in files:
        if file.endswith('_full.mid'):
            # Construct full file path
            file_path = os.path.join(root, file)
            # Copy the file to the target directory
            shutil.copy(file_path, target_dir)

print("All files ending in '_full.mid' have been copied to the 'musicDataset' directory.")

# list all files in 'musicDatasetOriginal' directory
print(os.listdir('./musicDatasetOriginal'))

# Commented out IPython magic to ensure Python compatibility.
# %run /content/finalAssignment_musicDataset/midi2text.py

# verifying content of input_melodies.txt
with open('/content/finalAssignment_musicDataset/inputMelodies.txt', 'r') as f:
    for line in f:
        print(line.strip())

# augmentedMidiTranslations
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 26 16:06:10 2024

@author: Giovanni Di Liberto
See description in the assignment instructions.
"""
import random
from itertools import groupby

# Define the note dictionary
NOTE_FREQUENCIES = {
    'C': 261.63,
    'c': 277.18,  # C#
    'D': 293.66,
    'd': 311.13,  # D#
    'E': 329.63,
    'F': 349.23,
    'f': 369.99,  # F#
    'G': 392.00,
    'g': 415.30,  # G#
    'A': 440.00,
    'a': 466.16,  # A#
    'B': 493.88,
}

# List of notes in order
NOTES = ['C', 'c', 'D', 'd', 'E', 'F', 'f', 'G', 'g', 'A', 'a', 'B']

def translate_notes(notes, shift):
    translated_notes = []
    for note in notes:
        if note in NOTES:
            index = NOTES.index(note)
            new_index = (index + shift) % len(NOTES)
            translated_notes.append(NOTES[new_index])
        else:
            translated_notes.append(note)  # Keep the character as is if it's not a note
    return ''.join(translated_notes)


# add rhythm variations function
def rhythm_variations(sequence, rest_probability=0.2):
  """
  introduces rhythm variations by adding random rests between notes

  args
  sequence(str): original melody as space-separated string of notes
  rest_probability(float): probability of adding a rest between notes

  returns
  str: rhythm variations melody
  """
  modified_sequence = []
  for token in sequence.split():
    modified_sequence.append(token)
    # add random rests
    if random.random() < rest_probability:
      modified_sequence.append('R')
  return ' '.join(modified_sequence)

def group_into_phrases(sequence, phrase_length=4):
  """
  group notes into phrases of specified lengh
  args
  sequence(str): original melody as space-separated string of notes
  phrase_length(int): number of notes per phrase

  helps model learn relationships between groups of notes (phrases)
  rather than individual notes

  returns
  str: melody grouped into phrases
  """
  tokens = sequence.split()
  phrases = [''.join(tokens[i:i+phrase_length]) for i in range(0, len(tokens), phrase_length)]
  return ' '.join(phrases)

def compact_tokenization(sequence):
    """
    shortens repeated notes in the sequence

    Args:
    sequence (str): melody as space-separated string of notes

    Returns:
    str: shortened tokenized melody
    """
    if not sequence.strip():  # handle empty or whitespace-only input
        return ""

    tokens = sequence.split()  # split melody into individual notes
    compacted = []

    for token, group in groupby(tokens):
        count = len(list(group))  # count consecutive occurrences of the token
        if count > 1:
            compacted.append(f"{token}*{count}")
        else:
            compacted.append(token)

    return ' '.join(compacted)

def reverse_melody(sequence):
    """
    reverses the order of the notes in the melody.

    Args:
        sequence (str): Melody as a space-separated string of notes.

    Returns:
        str: Reversed melody sequence.
    """
    return ' '.join(sequence.split()[::-1])

def scale_pitch(sequence, scale_factor):
    """
    Scales the pitch of the notes in the sequence by a given factor.

    Args:
        sequence (str): Melody as a space-separated string of notes.
        scale_factor (int): Number of semitones to scale (positive or negative).

    Returns:
        str: Scaled melody sequence.
    """
    scaled_sequence = []
    for token in sequence.split():
        if token in NOTES:  # Only scale valid notes
            index = NOTES.index(token)
            new_index = (index + scale_factor) % len(NOTES)
            scaled_sequence.append(NOTES[new_index])
        else:
            scaled_sequence.append(token)  # Leave rests or unknown tokens unchanged
    return ' '.join(scaled_sequence)


# Example usage
#input_notes = "CDE"
#shift = 1
#output_notes = translate_notes(input_notes, shift)
#print(output_notes)  # Output: cdF


# Load the input file
with open('/content/inputMelodies.txt', 'r') as file:
    input_melodies = file.readlines()

# Apply 5 different translations and save the results
shifts = [1, 2, 3, 4, 5]
augmented_melodies = []

max_examples = 3
count = 0

for shift in shifts:
    for melody in input_melodies:
        # augmented_melodies.append(translate_notes(melody.strip(), shift))
        # apply pitch transposition
        transposed_melody = translate_notes(melody.strip(), shift)
        # scale pitch
        scaled_melody = scale_pitch(transposed_melody, scale_factor=random.randint(-2, 2))
        # apply rhythm variations
        augmented_rhythm = rhythm_variations(scaled_melody, rest_probability=0.15)
        # augmented_rhythm = rhythm_variations(transposed_melody, rest_probability=0.15)

        reversed_melody = reverse_melody(augmented_rhythm)

        grouped_notes = group_into_phrases(reversed_melody, phrase_length=4)
        # grouped_notes = group_into_phrases(augmented_rhythm, phrase_length=4)


        compacted_melody = compact_tokenization(grouped_notes)

        if count < max_examples:
          print(f"Original melody: {melody.strip()}")
          print(f"Transposed melody: {transposed_melody}")
          print(f"Scaled melody: {scaled_melody}")
          print(f"Rhythm-augmented melody: {augmented_rhythm}")
          print(f"Grouped melody: {grouped_notes}")
          print(f"Reversed melody: {reversed_melody}")
          print(f"Compacted melody: {compacted_melody}")
          print("Appended Melody:", compacted_melody)
          print('-' * 50)
          count += 1


        augmented_melodies.append(compacted_melody)

# Save the augmented melodies to a new file
with open('inputMelodiesAugmented.txt', 'w') as file:
    for melody in augmented_melodies:
        file.write(melody + '\n')

# test rhythm variations
melody = "C D E F G A B"
transposed = translate_notes(melody, 1)
augmented_melody = rhythm_variations(melody, rest_probability=0.3)
# print("Original melody:", melody)
# print(f"Transposed melody: {transposed}")
# print("Rhythm-augmented melody:", augmented_melody)

# test grouped phrases
melody = "C D E F G A B R C D E F G A B R"
grouped = group_into_phrases(melody, phrase_length=4)
# print("Original melody:", melody)
# print("Grouped melody:", grouped)

# test compacted melody
melody = "C C C D E E F F F F G G G G G A B B B"
compacted = compact_tokenization(melody)
# print("Original melody:", melody)
# print("Compacted melody:", compacted)

sample_melody = "R R R R R R F G F E D C G A G F A A A G F G F D D C G A G F"
# Transpose notes
transposed_sample = translate_notes(sample_melody, 2)

# Add rhythm variations
augmented_rhythm_sample = rhythm_variations(transposed_sample, rest_probability=0.15)

# Group into phrases
grouped_sample = group_into_phrases(augmented_rhythm_sample, phrase_length=4)

# Compact repeated tokens
compacted_sample = compact_tokenization(grouped_sample)

# Print results
print("Original Melody new test:", sample_melody)
print("Transposed Melody new test:", transposed_sample)
print("Rhythm-Augmented Melody new test:", augmented_rhythm_sample)
print("Grouped Melody new test:", grouped_sample)
print("Compacted Melody new test:", compacted_sample)

print("The augmented melodies have been saved to inputMelodiesAugmented.txt")

# verifying content of inputMelodiesAugmented.txt
with open('/content/inputMelodiesAugmented.txt', 'r') as f:
  for line in f:
    print(line.strip())

# with open('/content/inputMelodiesAugmented.txt') as f:
#     contents = f.read()
#     print(contents)

# gpt.py
import torch
import torch.nn as nn
from torch.nn import functional as F
from collections import defaultdict, Counter
import numpy as np
import random
import math
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.spatial.distance import cdist
import zlib
from difflib import SequenceMatcher
import nltk
from torch.optim.lr_scheduler import CosineAnnealingLR

# hyperparameters
# batch_size = 64 # how many independent sequences will we process in parallel?
batch_size = 32
# block_size = 256 # what is the maximum context length for predictions?
block_size = 192
max_iters = 5000
eval_interval = 500
learning_rate = 1e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
# n_embd = 384
n_embd = 384
# n_head = 6
# n_layer = 6
n_head = 6
n_layer = 8
dropout = 0.3
# ------------


torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('/content/inputMelodiesAugmented.txt', 'r', encoding='utf-8') as f:
    text = f.read()


# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]


# Function to calculate token distribution
def calculate_token_distribution(tokens):
    counter = Counter(tokens)
    total = sum(counter.values())
    return {token: count / total for token, count in counter.items()}

# Function to calculate KL Divergence
def calculate_kl_divergence(p, q):
    kl_div = 0
    for token, p_val in p.items():
        q_val = q.get(token, 1e-8)  # Handle missing tokens with smoothing
        kl_div += p_val * np.log(p_val / q_val)
    return kl_div

# Function to calculate diversity and repetition
def calculate_diversity_and_repetition(tokens, n=3):
    # Diversity: Unique token ratio
    unique_tokens = len(set(tokens))
    total_tokens = len(tokens)
    unique_ratio = unique_tokens / total_tokens if total_tokens > 0 else 0

    # Repetition: Count repeated n-grams
    ngrams = [tuple(tokens[i:i + n]) for i in range(len(tokens) - n + 1)]
    ngram_counts = Counter(ngrams)
    repeated_ngrams = sum(count - 1 for count in ngram_counts.values() if count > 1)
    repetition_ratio = repeated_ngrams / len(ngrams) if len(ngrams) > 0 else 0

    return unique_ratio, repetition_ratio


# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out


# from part 1
# class Head(nn.Module):
#     """ one head of self-attention """

#     def __init__(self, head_size):
#         super().__init__()
#         self.key = nn.Linear(n_embd, head_size, bias=False)
#         self.query = nn.Linear(n_embd, head_size, bias=False)
#         self.value = nn.Linear(n_embd, head_size, bias=False)
#         self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

#         self.dropout = nn.Dropout(dropout)

#     def forward(self, x):
#         # input of size (batch, time-step, channels)
#         # output of size (batch, time-step, head size)
#         B,T,C = x.shape
#         k = self.key(x)   # (B,T,hs)
#         q = self.query(x) # (B,T,hs)
#         # compute attention scores ("affinities")
#         wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
#         wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
#         wei = F.softmax(wei, dim=-1) # (B, T, T)
#         wei = self.dropout(wei)
#         # perform the weighted aggregation of the values
#         v = self.value(x) # (B,T,hs)
#         out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
#         return out

# part 2
class Head(nn.Module):
    """One head of self-attention with relative positional embeddings."""

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.pos_emb = nn.Parameter(torch.randn(block_size, head_size))  # Relative positional embeddings
        self.dropout = nn.Dropout(dropout)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)   # (B, T, head_size)
        q = self.query(x) # (B, T, head_size)
        v = self.value(x) # (B, T, head_size)

        # Compute attention scores with relative positional bias
        rel_pos_bias = self.pos_emb[:T, :]  # (T, head_size)
        rel_scores = q @ rel_pos_bias.T  # (B, T, T)
        wei = (q @ k.transpose(-2, -1)) / math.sqrt(k.shape[-1]) + rel_scores

        # Apply masking for causal attention
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)

        # Perform the weighted aggregation
        out = wei @ v
        return out


class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        # better init, not covered in the original GPT video, but important, will cover in followup video
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

# part 2
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_iters)


for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    scheduler.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
generated_melody = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_melody)
#open('more.txt', 'w').write(decode(m.generate(context, max_new_tokens=10000)[0].tolist()))

# N-gram model class
# looks at previous (n-1) tokens to predict next item in melody sequence
class NGramModel:
    def __init__(self, n):
        self.n = n
        self.ngrams = defaultdict(Counter)

    def train(self, tokens):
        for i in range(len(tokens) - self.n):
            context = tuple(tokens[i:i + self.n - 1])
            next_token = tokens[i + self.n - 1]
            self.ngrams[context][next_token] += 1

    def generate(self, start_tokens, length):
        current_context = tuple(start_tokens[-(self.n - 1):])
        generated = list(start_tokens)

        for _ in range(length):
            if current_context in self.ngrams:
                next_token = self._sample_next_token(current_context)
            else:
                next_token = random.choice(list(self.ngrams.keys()))[0]

            generated.append(next_token)
            current_context = tuple(generated[-(self.n - 1):])

        return generated

    def _sample_next_token(self, context):
        next_tokens = self.ngrams[context]
        total = sum(next_tokens.values())
        choices, weights = zip(*next_tokens.items())
        return random.choices(choices, weights=[w / total for w in weights])[0]

    def calculate_perplexity(self, tokens):
        log_prob_sum = 0
        num_tokens = 0

        for i in range(len(tokens) - self.n):
            context = tuple(tokens[i:i + self.n - 1])
            next_token = tokens[i + self.n - 1]

            if context in self.ngrams and next_token in self.ngrams[context]:
                prob = self.ngrams[context][next_token] / sum(self.ngrams[context].values())
                log_prob_sum += -torch.log2(torch.tensor(prob))
                num_tokens += 1

        perplexity = torch.exp2(log_prob_sum / num_tokens) if num_tokens > 0 else float('inf')
        return perplexity

# Initialize and train n-gram model
ngram_model = NGramModel(n=3)
ngram_model.train(list(data.numpy()))

# Evaluate perplexity on train and validation sets
train_perplexity = ngram_model.calculate_perplexity(list(train_data.numpy()))
val_perplexity = ngram_model.calculate_perplexity(list(val_data.numpy()))

print(f"N-Gram Model Perplexity:\nTrain: {train_perplexity:.2f}\nValidation: {val_perplexity:.2f}")

# Generate melody using n-gram model
start_sequence = list(train_data[:3].numpy())  # Use the first few tokens as the starting context
generated_ngram = ngram_model.generate(start_sequence, length=100)
generated_melody_ngram = decode(generated_ngram)
print(f"Generated Melody (N-Gram):\n{generated_melody_ngram}")

# Calculate token distributions
train_distribution = calculate_token_distribution(train_data.numpy())
gpt_generated = m.generate(torch.zeros((1, 1), dtype=torch.long, device=device), max_new_tokens=100).squeeze().tolist()
gpt_distribution = calculate_token_distribution(gpt_generated)
ngram_distribution = calculate_token_distribution(generated_ngram)

# Compare distributions using KL Divergence
kl_div_gpt = calculate_kl_divergence(train_distribution, gpt_distribution)
kl_div_ngram = calculate_kl_divergence(train_distribution, ngram_distribution)

print(f"KL Divergence from Training Data:\nGPT Model: {kl_div_gpt:.4f}\nN-Gram Model: {kl_div_ngram:.4f}")

def plot_token_distributions(train_dist, gpt_dist, ngram_dist, top_n=20):
    # Sort tokens by their probability in the training data
    tokens = sorted(train_dist.keys(), key=lambda t: train_dist[t], reverse=True)[:top_n]

    # Get probabilities for the tokens
    train_values = [train_dist.get(t, 0) for t in tokens]
    gpt_values = [gpt_dist.get(t, 0) for t in tokens]
    ngram_values = [ngram_dist.get(t, 0) for t in tokens]

    # Convert tokens to musical notes using the itos mapping
    token_labels = [itos[token] for token in tokens]

    # Plot the distributions
    x = range(len(tokens))
    plt.figure(figsize=(12, 6))
    plt.bar(x, train_values, width=0.3, label='Training Data', align='center')
    plt.bar([p + 0.3 for p in x], gpt_values, width=0.3, label='GPT Model', align='center')
    plt.bar([p + 0.6 for p in x], ngram_values, width=0.3, label='N-Gram Model', align='center')

    # Update the x-axis labels with musical notes
    plt.xticks([p + 0.3 for p in x], token_labels, rotation=90)
    plt.ylabel('Token Probability')
    plt.title('Token Distribution Comparison')
    plt.legend()
    plt.tight_layout()
    plt.show()

# Call the function with token distributions
plot_token_distributions(train_distribution, gpt_distribution, ngram_distribution)

# Create a pairwise similarity matrix
def calculate_similarity_matrix(data, gpt_seq, ngram_seq, n=3):
    def ngram_set(seq, n):
        return set(tuple(seq[i:i + n]) for i in range(len(seq) - n + 1))

    data_ngrams = ngram_set(data, n)
    gpt_ngrams = ngram_set(gpt_seq, n)
    ngram_ngrams = ngram_set(ngram_seq, n)

    matrix = [
        [len(data_ngrams & data_ngrams) / len(data_ngrams),
         len(data_ngrams & gpt_ngrams) / len(data_ngrams),
         len(data_ngrams & ngram_ngrams) / len(data_ngrams)],
        [len(gpt_ngrams & data_ngrams) / len(gpt_ngrams),
         len(gpt_ngrams & gpt_ngrams) / len(gpt_ngrams),
         len(gpt_ngrams & ngram_ngrams) / len(gpt_ngrams)],
        [len(ngram_ngrams & data_ngrams) / len(ngram_ngrams),
         len(ngram_ngrams & gpt_ngrams) / len(ngram_ngrams),
         len(ngram_ngrams & ngram_ngrams) / len(ngram_ngrams)],
    ]

    return matrix

# Plot heatmap
similarity_matrix = calculate_similarity_matrix(
    train_data.numpy(), gpt_generated, generated_ngram, n=3
)

sns.heatmap(similarity_matrix, annot=True, xticklabels=['Train', 'GPT', 'N-Gram'],
            yticklabels=['Train', 'GPT', 'N-Gram'], cmap="YlGnBu", fmt=".2f")
plt.title('Sequence Similarity (n-gram Overlap)')
plt.show()


def calculate_diversity_and_repetition(tokens, n=3):
    # Diversity: Unique token ratio
    unique_tokens = len(set(tokens))
    total_tokens = len(tokens)
    unique_ratio = unique_tokens / total_tokens if total_tokens > 0 else 0

    # Repetition: Count repeated n-grams
    ngrams = [tuple(tokens[i:i + n]) for i in range(len(tokens) - n + 1)]
    ngram_counts = Counter(ngrams)
    repeated_ngrams = sum(count - 1 for count in ngram_counts.values() if count > 1)
    repetition_ratio = repeated_ngrams / len(ngrams) if len(ngrams) > 0 else 0

    return unique_ratio, repetition_ratio

def calculate_shannon_entropy(tokens):
    counts = Counter(tokens)
    probabilities = [count / sum(counts.values()) for count in counts.values()]
    return -sum(p * np.log2(p) for p in probabilities if p > 0)

def calculate_pitch_and_rhythm_similarity(original, generated):
    # Count occurrences of pitch and rhythm tokens
    original_counts = Counter(original)
    generated_counts = Counter(generated)

    # Normalize to get probabilities
    total_original = sum(original_counts.values())
    total_generated = sum(generated_counts.values())

    original_dist = {k: v / total_original for k, v in original_counts.items()}
    generated_dist = {k: v / total_generated for k, v in generated_counts.items()}

    # KL Divergence
    kl_div = calculate_kl_divergence(original_dist, generated_dist)

    # Earth Mover's Distance (using scipy)
    original_array = np.array([[original_dist.get(k, 0)] for k in original_dist.keys()])
    generated_array = np.array([[generated_dist.get(k, 0)] for k in original_dist.keys()])
    emd = cdist(original_array, generated_array, metric='euclidean').sum()

    return kl_div, emd

def calculate_transition_matrix(tokens, vocab_size):
    matrix = np.zeros((vocab_size, vocab_size))
    for i in range(len(tokens) - 1):
        matrix[tokens[i], tokens[i + 1]] += 1
    row_sums = matrix.sum(axis=1, keepdims=True)
    return matrix / np.maximum(row_sums, 1)  # Normalize rows to probabilities

def calculate_compression_ratio(sequence):
    original_size = len(sequence)
    compressed_size = len(zlib.compress(bytes(sequence)))
    return compressed_size / original_size

def calculate_self_similarity_matrix(sequence):
    length = len(sequence)
    matrix = np.zeros((length, length))
    for i in range(length):
        for j in range(length):
            matrix[i, j] = 1 if sequence[i] == sequence[j] else 0
    return matrix

# Metrics Implementation for N-Gram Baseline
ngram_generated = ngram_model.generate(list(train_data[:3].numpy()), length=100)

# Pitch and Rhythm Similarity
kl_div_ngram, emd_ngram = calculate_pitch_and_rhythm_similarity(train_data.numpy(), ngram_generated)

# Calculate the transition matrix for the training data
original_matrix = calculate_transition_matrix(train_data.numpy(), vocab_size)

# Transition Matrix Consistency
ngram_transition_matrix = calculate_transition_matrix(ngram_generated, vocab_size)
ngram_transition_consistency = np.linalg.norm(original_matrix - ngram_transition_matrix, ord='fro')

# Unique Token Usage
ngram_entropy = calculate_shannon_entropy(ngram_generated)

# Compression Ratio
ngram_compression = calculate_compression_ratio(ngram_generated)

# Self-Similarity
ngram_similarity = calculate_self_similarity_matrix(ngram_generated)

# Print Baseline Results
print(f"N-Gram Model Metrics:")
print(f"- KL Divergence: {kl_div_ngram}")
print(f"- EMD: {emd_ngram}")
print(f"- Transition Consistency: {ngram_transition_consistency}")
print(f"- Shannon Entropy: {ngram_entropy}")
print(f"- Compression Ratio: {ngram_compression}")


# evaluation metrics

def calculate_sdi(input_melody, output_melody):
    """Calculate Sequence Divergence Index (SDI)"""
    # tokenize melodies into unique sets of notes
    input_set = set(input_melody)
    output_set = set(output_melody)

    # calculate Jaccard similarity
    intersection = len(input_set.intersection(output_set))
    union = len(input_set.union(output_set))
    jaccard_similarity = intersection / union if union > 0 else 0

    # SDI is 1 - Jaccard similarity
    sdi = 1 - jaccard_similarity
    return sdi

def calculate_rcs(melody):
    """Calculate Rhythmic Complexity Score (RCS)"""
    # count consecutive occurrences of each note (simulating rhythm)
    rhythm = []
    current_note = None
    count = 0

    for note in melody:
        if note == current_note:
            count += 1
        else:
            if current_note is not None:
                rhythm.append(count)
            current_note = note
            count = 1
    if count > 0:
        rhythm.append(count)

    # Calculate entropy
    total_rhythm = sum(rhythm)
    probs = [r / total_rhythm for r in rhythm]
    entropy = -sum(p * np.log2(p) for p in probs if p > 0)

    # Normalize by the maximum possible entropy
    max_entropy = np.log2(len(rhythm)) if len(rhythm) > 0 else 1
    rcs = entropy / max_entropy
    return rcs

# Load input melody for comparison
with open('/content/inputMelodies.txt', 'r', encoding='utf-8') as f:
    input_melody = f.read()

# Tokenize melodies
input_tokens = [char for char in input_melody if char.isalpha()]
output_tokens = [char for char in generated_melody if char.isalpha()]

# Compute SDI and RCS
sdi_score = calculate_sdi(input_tokens, output_tokens)
rcs_score = calculate_rcs(output_tokens)

print(f"Sequence Divergence Index (SDI): {calculate_sdi(input_melody, output_tokens)}")
print(f"Rhythmic Complexity Score (RCS): {calculate_rcs(output_tokens)}")

sdi_gpt = calculate_sdi(input_tokens, [char for char in generated_melody if char.isalpha()])
rcs_gpt = calculate_rcs([char for char in generated_melody if char.isalpha()])

sdi_ngram = calculate_sdi(input_tokens, [char for char in generated_melody_ngram if char.isalpha()])
rcs_ngram = calculate_rcs([char for char in generated_melody_ngram if char.isalpha()])

# Assume training data is the input melody for baseline
sdi_train = calculate_sdi(input_tokens, input_tokens)
rcs_train = calculate_rcs(input_tokens)

# Visualization
models = ['Training Data', 'GPT Model', 'N-Gram Model']
rcs_scores = [rcs_train, rcs_gpt, rcs_ngram]

# Plot the scores
fig, ax = plt.subplots(figsize=(10, 6))

# Line plot for RCS
ax.plot(models, rcs_scores, 'r-o', label='RCS', linewidth=2, markersize=8, color='red')
ax.set_ylabel('RCS (Rhythmic Complexity Score)', color='red')
ax.tick_params(axis='y', labelcolor='red')
ax.set_ylim(0, 1)

# Title and legend
plt.title('Comparison of RCS Scores Across Models')
ax.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))
plt.tight_layout()
plt.show()

def calculate_tsi(melody, scale):
    """Calculate Tonal Stability Index."""
    in_scale = sum(1 for note in melody if note in scale)
    return in_scale / len(melody) if len(melody) > 0 else 0

scale = set('CDEFGAB')
tsi_score = calculate_tsi(output_tokens, scale)
print(f"Tonal Stability Index (TSI): {tsi_score:.4f}")

import matplotlib.pyplot as plt
import re


def get_rhythm_distribution(sequence):
    """Calculate the distribution of rhythmic patterns (note durations and rests)"""
    durations = Counter(sequence)  # Assuming sequence encodes durations or 'R' for rests
    return durations

def calculate_rest_ratio(sequence):
    """Calculate the ratio of rests to total notes in the sequence"""
    total_notes = len(sequence)
    rest_count = sequence.count('R')
    return rest_count / total_notes if total_notes > 0 else 0

def calculate_pitch_range(sequence):
    """Calculate the pitch range (difference between highest and lowest pitch)"""
    NOTES = ['C', 'c', 'D', 'd', 'E', 'F', 'f', 'G', 'g', 'A', 'a', 'B']

    def note_to_semitones(note):
        return NOTES.index(note) if note in NOTES else None

    pitches = [note_to_semitones(note) for note in sequence if note in NOTES]
    if pitches:
        return max(pitches) - min(pitches)
    return 0

def get_repeated_pattern_frequency(sequence, n=3):
    """Calculate the frequency of repeated n-note patterns"""
    ngrams = [tuple(sequence[i:i + n]) for i in range(len(sequence) - n + 1)]
    ngram_counts = Counter(ngrams)
    repeated_patterns = {pattern: count for pattern, count in ngram_counts.items() if count > 1}
    return repeated_patterns


def calculate_leap_to_step_ratio(sequence):
    """Calculate the ratio of leaps to steps in the melody"""
    NOTES = ['C', 'c', 'D', 'd', 'E', 'F', 'f', 'G', 'g', 'A', 'a', 'B']

    def note_to_semitones(note):
        return NOTES.index(note) if note in NOTES else None

    notes = list(sequence)
    leaps, steps = 0, 0

    for i in range(len(notes) - 1):
        current_note = notes[i]
        next_note = notes[i + 1]

        if current_note == 'R' or next_note == 'R':
            continue

        current_semitones = note_to_semitones(current_note)
        next_semitones = note_to_semitones(next_note)

        if current_semitones is not None and next_semitones is not None:
            interval = abs(next_semitones - current_semitones)
            if interval > 2:
                leaps += 1
            else:
                steps += 1

    total = leaps + steps
    return leaps / total if total > 0 else 0


def calculate_motif_coverage(training_melodies, generated_sequence, n=3):
    """Calculate the proportion of motifs from the training data found in the generated sequence"""
    def extract_ngrams(sequence, n):
        return set(tuple(sequence[i:i + n]) for i in range(len(sequence) - n + 1))

    training_motifs = set()
    for melody in training_melodies:
        training_motifs.update(extract_ngrams(melody, n))

    generated_motifs = extract_ngrams(generated_sequence, n)
    matching_motifs = training_motifs & generated_motifs

    return len(matching_motifs) / len(training_motifs) if training_motifs else 0


def expand_compact_tokens(sequence):
    """
    Expand compact tokens of the form RRRR*2 back to their original repeated sequences.
    """
    expanded_sequence = []

    # Split the sequence into individual tokens
    tokens = sequence.split()

    for token in tokens:
        # Check if the token matches the compact pattern (e.g., RRRR*2)
        match = re.match(r'(.*?)\*(\d+)', token)
        if match:
            base = match.group(1)  # The base token (e.g., RRRR)
            repeat_count = int(match.group(2))  # The repeat count (e.g., 2)
            expanded_sequence.extend([base] * repeat_count)  # Expand the token
        else:
            expanded_sequence.append(token)  # Keep non-compact tokens as-is

    return ' '.join(expanded_sequence)

# Example compact sequence
compact_sequence = "RRRR*2 CCCC RRRR*3 DDDD"

# Expand compact tokens
expanded_sequence = expand_compact_tokens(compact_sequence)

print("Compact Sequence:", compact_sequence)
print("Expanded Sequence:", expanded_sequence)


# Ensure valid tokens
gpt_generated = [token for token in gpt_generated if token in itos]
ngram_generated = [token for token in generated_ngram if token in itos]

# Update decode to handle invalid tokens
decode = lambda l: ''.join([itos.get(i, '?') for i in l])

print("Raw GPT-Generated Tokens:", gpt_generated[:100])
print("Length of GPT-Generated Tokens:", len(gpt_generated))

# Expand compact tokens
decoded_gpt_generated = expand_compact_tokens(decode(gpt_generated))
decoded_ngram_generated = expand_compact_tokens(decode(ngram_generated))
decoded_training_data = expand_compact_tokens(decode(train_data.numpy()))

# Print for debugging
print("Decoded GPT-Generated Melody:", decoded_gpt_generated[:100])
print("Decoded N-Gram Generated Melody:", decoded_ngram_generated[:100])
print("Decoded Training Data (First 100 Notes):", decoded_training_data[:100])
print("Length of GPT-Generated Decoded Melody:", len(decoded_gpt_generated))


# Metrics for GPT Model
print("Metrics for GPT-Generated Melody:")
gpt_rhythm_dist = get_rhythm_distribution(decoded_gpt_generated)
gpt_rest_ratio = calculate_rest_ratio(decoded_gpt_generated)
gpt_pitch_range = calculate_pitch_range(decoded_gpt_generated)
gpt_repeated_patterns = get_repeated_pattern_frequency(decoded_gpt_generated, n=3)
gpt_leap_to_step_ratio = calculate_leap_to_step_ratio(decoded_gpt_generated)
gpt_motif_coverage = calculate_motif_coverage([decoded_training_data], decoded_gpt_generated, n=3)

print("Rhythm Distribution:", gpt_rhythm_dist)
print("Rest Ratio:", gpt_rest_ratio)
print("Pitch Range:", gpt_pitch_range)
print("Repeated Patterns:", gpt_repeated_patterns)
print("Leap-to-Step Ratio:", gpt_leap_to_step_ratio)
print("Motif Coverage:", gpt_motif_coverage)

# Metrics for N-Gram Model
print("\nMetrics for N-Gram Generated Melody:")
ngram_rhythm_dist = get_rhythm_distribution(decoded_ngram_generated)
ngram_rest_ratio = calculate_rest_ratio(decoded_ngram_generated)
ngram_pitch_range = calculate_pitch_range(decoded_ngram_generated)
ngram_repeated_patterns = get_repeated_pattern_frequency(decoded_ngram_generated, n=3)
ngram_leap_to_step_ratio = calculate_leap_to_step_ratio(decoded_ngram_generated)
ngram_motif_coverage = calculate_motif_coverage([decoded_training_data], decoded_ngram_generated, n=3)

print("Rhythm Distribution:", ngram_rhythm_dist)
print("Rest Ratio:", ngram_rest_ratio)
print("Pitch Range:", ngram_pitch_range)
print("Repeated Patterns:", ngram_repeated_patterns)
print("Leap-to-Step Ratio:", ngram_leap_to_step_ratio)
print("Motif Coverage:", ngram_motif_coverage)

# melodyPlay.py
# -*- coding: utf-8 -*-
"""
@author: Giovanni Di Liberto
See description in the assignment instructions.
"""

from pydub import AudioSegment
import numpy as np
import simpleaudio as sa

# Define note frequencies (A4 = 440 Hz)
#NOTE_FREQUENCIES = {
#    'C': 261.63,
#    'D': 293.66,
#    'E': 329.63,
#    'F': 349.23,
#    'G': 392.00,
#    'A': 440.00,
#    'B': 493.88,
#    'R': 0  # Rest (no sound)
#}

NOTE_FREQUENCIES = {
    'C': 261.63,
    'c': 277.18,  # C#
    'D': 293.66,
    'd': 311.13,  # D#
    'E': 329.63,
    'F': 349.23,
    'f': 369.99,  # F#
    'G': 392.00,
    'g': 415.30,  # G#
    'A': 440.00,
    'a': 466.16,  # A#
    'B': 493.88,
    'R': 0     # Rest
}


# Generate a sine wave for a given frequency
def generate_sine_wave(frequency, duration_ms, sample_rate=44100, amplitude=0.5):
    t = np.linspace(0, duration_ms / 1000, int(sample_rate * duration_ms / 1000), False)
    wave = 0.5 * amplitude * np.sin(2 * np.pi * frequency * t)
    wave = (wave * 32767).astype(np.int16)
    audio_segment = AudioSegment(
        wave.tobytes(),
        frame_rate=sample_rate,
        sample_width=wave.dtype.itemsize,
        channels=1
    )
    return audio_segment

# Function to create a sequence of notes
def create_sequence(note_sequence, duration_ms=500):
    song = AudioSegment.silent(duration=0)
    for note in note_sequence:
        if note == 'R':  # Handle rest
            segment = AudioSegment.silent(duration=duration_ms)
        else:
            frequency = NOTE_FREQUENCIES[note]
            segment = generate_sine_wave(frequency, duration_ms)
        song += segment
    return song

# Example sequence (You can replace this with your sequence)
# sequence = "C C G G A A G F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C".split()
# sequence = "BDDgEARagadGCCdddEgfgcDEAGBDEFgA"
# sequence = "AdGaRaaaCaCdRaRaaRRRaaaaaRGGaFdgRaRaRRdDFRFaDRRaaFRRRRRRRdFRddDFagGRRdRadRFRRRGGaGFgGFGF"
# sequence = "DEEDRDDERcBARcRBcREDR"
# sequence = "RcREDcBcAfRcccEDBcABcEEEERDRDDEERRcBccRccBccBcccBcRcBcccRREEDEDE"
sequence = "EEEEREEDDcRcBBBBARAfBBBBCDBRBAAABDBRADBfEEDDDRDEREEEDDccRBccRDBBABRAARAfBRBBBABfBRBBcBAAAAAf"

# Create the sequence
song = create_sequence(sequence, duration_ms=500)  # 500ms per note

# Save the song to a .wav file
song.export("nursery_rhyme.wav", format="wav")

# Play the .wav file using simpleaudio
wave_obj = sa.WaveObject.from_wave_file("nursery_rhyme.wav")
play_obj = wave_obj.play()
play_obj.wait_done()

# -*- coding: utf-8 -*-
"""
@author: Giovanni Di Liberto
See description in the assignment instructions.
"""

import os
from mido import MidiFile, MidiTrack, Message

# Define the note dictionary
NOTE_FREQUENCIES = {
    'C': 261.63,
    'c': 277.18,  # C#
    'D': 293.66,
    'd': 311.13,  # D#
    'E': 329.63,
    'F': 349.23,
    'f': 369.99,  # F#
    'G': 392.00,
    'g': 415.30,  # G#
    'A': 440.00,
    'a': 466.16,  # A#
    'B': 493.88,
}

# Map MIDI note numbers to note names (ignoring octaves)
MIDI_NOTE_TO_NAME = {
    0: 'C', 1: 'c', 2: 'D', 3: 'd', 4: 'E', 5: 'F', 6: 'f', 7: 'G', 8: 'g', 9: 'A', 10: 'a', 11: 'B'
}

# Function to convert MIDI file to text sequence
def midi_to_text_sequence(midi_path):
    midi = MidiFile(midi_path)
    sequence = []
    last_note_time = 0

    for track in midi.tracks:
        for msg in track:
            if msg.type == 'note_on' and msg.velocity > 0:
                note = MIDI_NOTE_TO_NAME.get(msg.note % 12, '')  # Use modulo to map to the correct note
                if note:
                    # Add rests for the duration between the last note and the current note
                    if msg.time > last_note_time:
                        rest_duration = msg.time - last_note_time
                        num_rests = rest_duration // 480  # Assuming 480 ticks per beat
                        sequence.extend(['R '] * num_rests)
                    sequence.append(note)
                    sequence.append(' ')
                    last_note_time = msg.time

    # Remove consecutive rests
    sequence = [note for i, note in enumerate(sequence) if not (note == 'R' and i > 0 and sequence[i-1] == 'R')]

    return ''.join(sequence)

# Function to convert text sequence back to MIDI
def text_sequence_to_midi(sequence, output_path):
    midi = MidiFile()
    track = MidiTrack()
    midi.tracks.append(track)

    sequence = sequence.replace(' ', '') # removing spaces

    for note in sequence:
        if note == 'R':
            track.append(Message('note_off', note=0, velocity=0, time=480))
        else:
            midi_note = list(MIDI_NOTE_TO_NAME.keys())[list(MIDI_NOTE_TO_NAME.values()).index(note)]
            track.append(Message('note_on', note=midi_note+12*5, velocity=64, time=0))
            track.append(Message('note_off', note=midi_note+12*5, velocity=64, time=480))

    midi.save(output_path)

# Directory containing the MIDI files
midi_dir = 'musicDatasetOriginal'

# Directory to store the resulting MIDI files
output_dir = 'musicDatasetSimplified'

# Create the output directory if it doesn't exist
# if not os.path.exists(output_dir):
#     os.makedirs(output_dir)

# # List to store the text sequences
# text_sequences = []

# # Process each MIDI file in the directory
# for file_name in os.listdir(midi_dir):
#     if file_name.endswith('.mid'):
#         midi_path = os.path.join(midi_dir, file_name)
#         text_sequence = midi_to_text_sequence(midi_path)
#         if text_sequence:  # Check if the sequence is not empty
#             text_sequences.append(text_sequence)
#         else:
#             print(f"No notes found in {file_name}")  # Debugging output

# # Write the text sequences to a file
# with open("inputMelodies.txt", "w") as file:
#     for sequence in text_sequences:
#         file.write(sequence + "\n")

# # Convert text sequences back to MIDI files
# for i, sequence in enumerate(text_sequences):
#     output_path = os.path.join(output_dir, f"output_midi_{i+1}.mid")
#     text_sequence_to_midi(sequence, output_path)

# print("Text sequences have been written to inputMelodies.txt")
sequence = "RdGRRdaaCaCdRaRRdRRRaaaaaRGGaFdgFdRaRRdDFRFaDCaaaFGRRRRRRdFRCdCaagGdCCCadRCRRRGGaGGgGFGFGFGRFGdFFdFGGaaGaCRRRGFRaaDCaRRGRRFRRFRRFRFRRRgRRCCaaCRRaaAFRRaaRRRRaaaaRRaaFRRaGRdRGRdRGRdRGRdRGRdRGRdRGRdRGRdRGRdRGRdRGRdRGRdRGRdRRddFRdF"
text_sequence_to_midi(sequence, "output_midi_1.mid")
